/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package semp.cfg;

import picocli.CommandLine;
import semp.cfg.cli.SempCfgCommand;

public class App {
    public static void main(String[] args) {
        int exitCode = new CommandLine(new SempCfgCommand()).execute(args);
        System.exit(exitCode);
    }
}
