/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.solace.tools.sempcfg;

import picocli.CommandLine;
import com.solace.tools.sempcfg.cli.SempCfgCommand;

public class App {
    public static void main(String[] args) {
        int exitCode = new CommandLine(new SempCfgCommand()).execute(args);
        System.exit(exitCode);
    }
}
